export type WrittenFrags = {
    [key: string]: JSX.Element
}

export const texts: WrittenFrags = {
    "3": (<div className="p-14 text-2xl"><h2 className="text-4xl font-bold">Arrestation</h2><br/>- Messieurs, est-ce que je peux vous aider ? demanda nonchalamment Hautbrave.<br/> 
        - Boucle-là. C&apos;est nous qui posons les questions ici. On peut savoir ce que tu fais dans l&apos;coin ? Une dizaine d&apos;hommes avait pénétré le Bougainville, l&apos;un d&apos;entre eux, arborant une écharpe aux motifs travaillés s&apos;était avancé pour lui répondre.<br/> 
        - Eh bien je vogue ça et là, au gré des vents et des événements, serait-ce interdit ?<br/> 
        - Il se trouve que ça l&apos;est par chez nous. Rien à cacher ? demanda-t-il en lançant un coup d&apos;œil vers le vaisseau.<br/> 
        - J&apos;imagine que cela dépend de ce que vous cherchez mais enfin à priori non. Vous allez bien vous en…<br/> 
        - On va s&apos;en assurer. L&apos;homme fit un signe et deux soldats entrèrent plus profondément dans le Bougainville. Hautbrave affichait un air mi-amusé mi-circonspect qui avait l&apos;air d&apos;énerver l&apos;écharpe au plus haut point. Les deux hommes se regardèrent quelques instants sans rien dire avant que le capitaine ne se décide à briser le silence:<br/> 
        - Vous cherchez quelque chose… ou quelqu&apos;un en particulier ?<br/> 
        - On veut juste s&apos;assurer que vous n&apos;ayez rien à voir avec les Bleuches, et si c&apos;est le cas croyez-moi qu&apos;on détachera la tête de vos épaules, ça vous passera l&apos;envie de sourire.<br/> 
        - En effet, la perspective est peu réjouissante, rassurez-vous cependant, je ne sais même pas qui sont les Bleuches.<br/> 
        - Exactement ce que dirait quelqu&apos;un qui traite avec ces traîtres ! rétorqua l&apos;écharpe, perfide.<br/> 
        - Sans doute, également quelqu&apos;un qui ne sait même pas qui sont les Bleuches, vous en conviendrez, reprit Hautbrave sans quitter une légèreté qui agaçait beaucoup son interlocuteur.<br/> 
        - Nous verrons bien tout cela de toute façon.L&apos;homme à l&apos;écharpe écarta ainsi les remarques de Hautbrave et coupa court à la conversation. A nouveau, le silence se fit seulement interrompu par les bruits de la fouille des soldats. De temps en temps, Hautbrave jetait un coup d&apos;œil par dessus son épaule afin de voir si tout se passait bien, mais les soldats étaient plus loin dans le vaisseau. <br/> 
        - Dites, loin de moi l&apos;idée d&apos;insinuer que vous pourriez être un peu brute, mais enfin j&apos;espère que vos gars font attention.<br/> 
        - C&apos;est une menace ? répondit aussitôt l&apos;écharpe avec un sourire mauvais.<br/> 
        - Je n&apos;oserais pas bien sûr, c&apos;est votre écharpe, elle m&apos;impressionne bien trop.<br/> 
        - Vous moquez l&apos;écharpe de la très noble et excellente Ecclemos ? Puis sans attendre de réponse, et penchant la tête sur le côté pour appeler ses gars, il ordonna à ses hommes d&apos;embarquer le capitaine et de séquestrer le vaisseau.<br/>
        <br/>
        <h2 className="text-4xl font-bold">Assemblée Ecclemosienne</h2>
        <br/>
        Hautbrave fut mené sur une planète non loin, dans une grande et, il fallait bien le reconnaître, magnifique ville, ou, plus exactement, qui fut certainement magnifique et l&apos;était assurément encore, mais semblait à dessein salie, amochée, dans le sens de rendue moche, par de grossiers graffitis sur de superbes bâtiments, des toiles blanches cachant des pans entiers d&apos;architecture ou encore des statues, les rues jonchées de bouteilles et autres détritus, sans compter les rebuts de la société qui y cuvaient leur vin. L&apos;effervescence animait la ville, des groupes passaient ça et là, certains chantant et dansant, d&apos;autres clamant des slogans vindicatifs, d&apos;autres encore, traînaient des individus malchanceux dont le sort semblait scellé. L&apos;écharpe et ses hommes conduisirent Hautbrave devant ce qui avait dû être un palais, bâtiment aujourd&apos;hui très dégradé sur lequel était inscrit en lettres rouges au niveau du frontispice: &quot;<span className="text-red-900">Assemblée Ecclemosienne</span>&quot;. 
        Ils y pénétrèrent et gagnèrent un hémicycle où se trouvaient quelques centaines d&apos;individus passionnés, criant et jurant, agitant leurs membres pour huer leurs adversaires ou encourager leurs camarades. Echarpe fit un geste à ses hommes qui s&apos;arrêtèrent et alla parler à voix basse avec l&apos;un de ces énergumènes qui jeta un regard inquisiteur à Hautbrave, puis, quelques minutes plus tard, gagna le pupitre où les orateurs s&apos;adressaient à l&apos;Assemblée:<br/>&quot;<i>Ecclemosiens, au milieu de toutes nos réjouissances, et elles sont nombreuses, alors que nous portons haut l&apos;incandescente ardeur de l&apos;Ecclemos, et faisons reculer chaque jour davantage les ténèbres de l&apos;asservissement et de la haine, il nous faut craindre encore pour notre entreprise. A l&apos;évidence, le mal que nous combattons est tel, nous ne pouvons naïvement penser qu&apos;il n&apos;est pas déjà à l&apos;œuvre pour nous détruire, reprendre son trône et poursuivre son règne de terreur et d&apos;effroi. Chacun d&apos;entre nous doit faire montre de l&apos;attention la plus déterminée, vis-à-vis de lui-même, vis à vis de ses camarades ecclemosiens, vis-à-vis de tous ceux qui, sur notre territoire, ne font pas la démonstration la plus ardente de leur soutien à notre noble cause.</i>&quot; <br/>Au milieu de nombreuses acclamations, quelques murmures, un brouhaha même d&apos;un côté de l&apos;hémicycle monta des tribunes.<br/>
        “<i>Oh, je sais bien que certaines bonnes âmes s&apos;émeuvent de nos propositions, il leur faut urgemment prendre la mesure de la tâche qui est la nôtre, et du sacrifice qu&apos;elle demande. Qu&apos;ils se montrent clairvoyants et voient dans leurs rangs ceux qui s&apos;opposent à nos motions en arguant défendre la Liberté, lorsqu&apos;ils sont en réalité les serviteurs des tyrans. A l&apos;heure des comptes, il ne faudrait pas, pour leur réputation devant la population légitimement en colère, qu&apos;ils défendent les mêmes idées que ces traîtres. Il me faut cependant vous convaincre, vous, les justes et les bons, qui n&apos;avez que l&apos;erreur d&apos;être trop justes et trop bons, vous rendant aveugles à toutes les facéties du mal. Vous qui pensez notre victoire acquise et ne redoutez pas la force de nos ennemis, des ennemis de l&apos;Ecclemos, des ennemis de la justice et de la  vertu, découvrez le visage de l&apos;un de ses agents.</i>”<br/>En disant ses mots, il tendit le bras vers Hautbrave que l&apos;écharpe poussa dans le dos en lui intimant d&apos;avancer jusqu&apos;au pupitre. Hautbrave s&apos;exécuta en commençant à penser que ce qui ressemblait à une mauvaise blague prenait une tournure fort peu amusante. La salle explosa en voyant s&apos;avancer le capitaine, la terreur s&apos;afficha sur la plupart des visages, puis la haine, et les invectives tombaient sous le regard enchanté de l&apos;homme à la tribune.“<br/><i>Cet énergumène a été capturé par l&apos;Ecclemosien sergent Bashyk, reprit-il en déroulant élégamment son bras vers l&apos;écharpe, alors qu&apos;il professait son adhésion à la tyrannie en proférant des propos injurieux, que je vous épargne, contre l&apos;Ecclemos.</i>” 
        <br/>A ces mots, des “à mort !” et autres imprécations s&apos;élevèrent des gradins. L&apos;orateur agita ses bras en signe d&apos;apaisement: <br/>“<i>Du sang froid messieurs, s&apos;il vous plaît. Vous savez combien je suis engagé contre la tyrannie, pourtant, nous ne devons renoncer à nos principes, seuls garants de la justesse de notre combat. Aussi, cet énergumène, tout détestable qu&apos;il soit, et il l&apos;est assurément, aura droit à un jugement équitable au Tribunal d&apos;Exception de lutte contre la tyrannie. Ce n&apos;est qu&apos;à la lumière d&apos;un jugement validé par la sage réflexion de nos incorruptibles juges, que cet individu pourra, ou non, être mis à mort.</i>”<br/>
        “Il a raison ! Vive le Tribunal d&apos;Exception ! Vive la justice ! Vive l&apos;Ecclemos”. Les hourras et autres acclamations saluèrent comme il se devait ce discours réfléchi et néanmoins déterminé.
        <br/><br/>
        <h2 className="text-4xl font-bold">Tribunal d&apos;Exception</h2>
        <br/>
        Hautbrave fut embarqué par d&apos;autres soldats vers la sortie de l&apos;hémicycle pour être guidé, non loin de là, dans un grand couloir où on le fit attendre devant une belle porte en bois massif. Il y avait devant lui plusieurs accusés, certains en pleurs, d&apos;autres fermés et déterminés. Le capitaine fut témoin d&apos;une petite ronde bien huilée, un accusé rentrait quand un autre sortait, et tout cela ne prenait que quelques minutes. Aussi, l&apos;attente ne fut-elle pas bien longue. Hautbrave se retrouva devant un parterre de juges à l&apos;air mauvais. 
        “Bien, Ecclemosiens, veuillez conduire l&apos;accusé au pupitre, dit le président de la chambre en indiquant une petite barre au centre de la pièce. Merci. Etranger, vous êtes accusés par la Garde Ecclemosienne et l&apos;Assemblée Ecclemosienne d&apos;avoir partie liée avec la Tyrannie, de parler, d&apos;écrire et d&apos;agir contre l&apos;Ecclemos, de ridiculiser les fiers et nobles Ecclemosiens malgré les règles d&apos;hospitalité dont vous avez jouies, de fomenter des actions violentes contre les Ecclemosiens ou leurs institutions. Voilà des charges évidemment très lourdes, pour lesquelles il me semble que seule la condamnation à mort peut convenir. Qu&apos;avez-vous à dire pour votre défense ?” 
        Le capitaine affichait un air étonnamment calme. Bien qu&apos;il soit question de sa mise à mort, était-ce l&apos;habitude de la chose, ou le surréalisme de la situation dans laquelle il se trouvait, il ne parvenait pas à s&apos;inquiéter de quoi que ce soit. Au moment de prendre la parole, il pensa que c&apos;était sans doute lié à l&apos;absence totale d&apos;emprise qu&apos;il avait sur les événements. A l&apos;évidence les juges ne l&apos;écouteraient pas davantage que les autres et son destin était plus ou moins déjà scellé. A quoi bon, dès lors, paniquer ?<br/> 
        - “Messieurs les juges, je conteste l&apos;intégralité des charges retenues contre moi. Je me promène dans l&apos;univers et ne suis arrivé dans vos parsecs que très récemment, totalement ignorant des événements grandioses ou malheureux que vous vivez apparemment. Je ne suis au service d&apos;aucun tyran, et n&apos;ai aucune animosité ni envers votre Ecclemos, ni envers les… Ecclemosiens. Je n&apos;ai par ailleurs aucune velléité d&apos;action violente à leur encontre...<br/> 
        - Sommes-nous condamnés à écouter ces sornettes toute la journée ? interrompit le procureur général. Des mots, rien que des mots, eh quoi ? Rien pour les appuyer ? Aucun témoignage, aucun document ? Allons bon… Je voudrais appeler l&apos;Ecclemosien sergent Bashyk à la barre.<br/> 
        - Bien, nous attendons donc l&apos;Ecclemosien sergent Bashyk, confirma le président. L&apos;écharpe pénétra dans la salle d&apos;audience, et se dirigea vers la barre alors que Hautbrave était mené vers un banc sur le côté.<br/> 
        - Ecclemosien sergent Bashyk, vous êtes celui qui a arrêté ce dangereux individu avant qu&apos;il ne s&apos;adonne à quelque mauvaise action, pouvez-vous nous raconter les détails de son interpellation ?<br/> 
        - Bien sur Ecclemosien procureur général. Je me livrais avec mes hommes à un banal contrôle du vaisseau de l&apos;accusé, conformément aux consignes de l&apos;Assemblée Ecclemosienne pour surveiller les allers et venues des ennemis de l&apos;Ecclemos. Immédiatement, l&apos;accusé s&apos;est montré extrêmement réticent malgré le grand respect dont nous avons fait preuve. Il a plusieurs fois mis des bâtons dans les roues de mes hommes qui fouillaient son vaisseau, sans doute pour éviter que l&apos;on trouve quoi que ce soit d&apos;incriminant. Finalement, en criant “à bas l&apos;Ecclemos”, il a essayé de m&apos;agresser, et je ne dois mon salut qu&apos;à la réactivité et la loyauté de mes hommes, envers moi presque autant qu&apos;envers l&apos;Ecclemos.<br/> 
        - Voilà un récit édifiant. Lorsque vous dites “agresser”, Ecclemosien sergent, parlez-vous d&apos;une agression verbale ou physique ?<br/> 
        - Une agression, Ecclemosien procureur général.<br/> 
        - Je vois. Physique alors. Il nous faut rajouter à la liste des griefs “tentative de meurtre sur un représentant de l&apos;Ecclemos”. Ce sera tout, votre honneur Ecclemosienne.<br/> 
        - Merci. Accusé, si vous voulez bien reprendre place à la barre, et nous donner votre version avant que je ne rende mon verdict. Hautbrave se leva et prit la place du sergent.<br/> 
        - Rien de ce qui vient d&apos;être dit n&apos;est juste. Mon vaisseau est entre vos mains et j&apos;imagine que la fouille s&apos;est poursuivie depuis notre arrivée. Avez-vous trouvé quoi que ce soit qui prouverait ce que vous avancez ?<br/> 
        - Eh bien, Ecclemosien procureur général, voilà une bonne question, nous vous écoutons.<br/> 
        - Votre honneur Ecclemosienne, le vaisseau a été passé au peigne fin, sans que l&apos;on puisse trouver trace d&apos;une moindre preuve de proximité entre l&apos;accusé et la Tyrannie. Toutefois votre Honneur Ecclemosienne, j&apos;en conclue que nous avons affaire à un individu particulièrement dangereux et sournois qui aura su cacher les preuves de telle façon que même nos douaniers si talentueux et dévoués ne trouvassent rien. Aussi, bien loin d&apos;innocenter l&apos;accusé, l&apos;absence de preuve me semble tout au contraire être une preuve en soi de sa culpabilité.<br/> 
        - Une démonstration impressionnante, comme souvent, Ecclemosien procureur général. La cour déclare donc l&apos;accusé coupable, et le condamne à la peine capitale, qui sera exécutée demain. Ecclemosien greffier, veuillez noter.
        <br/><br/>
        <h2 className="text-4xl font-bold">Prison</h2>
        <br/>
        Hautbrave se retrouva dans une cellule sordide, humide, les murs tachés d&apos;une mousse verdâtre, les grilles rongées par la rouille, le sol jonché de choses et d&apos;autres que le capitaine s&apos;évertua à ne pas trop analyser. Il croupissait ainsi, dominé par le sentiment d&apos;un gigantesque gâchis, mourir en un tel décor quand il avait rencontré tant de dangers dans les merveilles de l&apos;univers. Par la petite ouverture grillagée, adossé au mur, il regardait le ciel et les innombrables étoiles qu&apos;il avait pris soin de nommer pour se mieux repérer. Son esprit se mêlait à tous ces noms en une danse hypnotisante, il relâcha ses épaules et laissa aller sa tête en arrière contre le mur moisi, son corps soudain perclus par la fatigue. Il ferma les paupières, visualisant tous les souvenirs heureux qu&apos;il avait vécu ces dernières années, un sourire aux lèvres. Une larme s&apos;échappa de son œil droit, coulant lentement le long de sa joue en une agréable sensation de fraîcheur. CLANG. La grille s&apos;ouvrit soudainement, Hautbrave n&apos;avait pas entendu les pas des trois hommes qui pénétraient maintenant dans sa cellule. L&apos;un d&apos;eux n&apos;était autre que l&apos;orateur qui avait enflammé les Ecclemosiens de l&apos;Assemblée.<br/> 
        - Enlevez-lui ses chaînes, gardez-le menotté.<br/> - Bien Ecclemosien député Mashata, répondirent les deux hommes qui accompagnaient l&apos;orateur. Les deux hommes s&apos;exécutèrent, attrapèrent Hautbrave par les bras, et le petit groupe traversa la prison étrangement vide jusqu&apos;à la sortie. Après s&apos;être assuré que tout était calme, ils poursuivirent leur chemin jusqu&apos;à un grand hangar non loin. <br/> 
        - Vive Mashata ! Vive l&apos;Ecclemos ! Les tyrans dans le Vide Froid ! Ecclemosien député Mashata, que faites-vous là ? demanda un homme visiblement éméché, centre d&apos;intérêt d&apos;une petite troupe d&apos;une dizaine d&apos;énergumènes tous dans un état plus ou moins similaire.<br/> - Ecclemosien ! Toujours au service de l&apos;Ecclemos, comme il convient. Vous aussi je vois.<br/> 
        - Bien sûr ! Ce n&apos;est que grâce à notre vigilance appuyée que les tyrans périront et que l&apos;Ecclemos triomphera ! On va s&apos;en assurer plus tard avec les gars, paraît que l&apos;Ecclemosien Yattafa s&apos;est montré réticent à célébrer les bienfaits de l&apos;Ecclemos.<br/> - L&apos;Ecclemos est fière de vous Ecclemosien ! Vous êtes de la race de ceux qui font triompher la justice.<br/> - Voudriez pas venir avec nous, ça ferait bien plaisir à tous les gars.<br/> - Hélas Ecclemosien, j&apos;ai moi-même une tâche à accomplir pour l&apos;Ecclemos. Je vais vous laisser.<br/> 
        - Ils piaillent pas beaucoup vos amis, faut bien célébrer l&apos;Ecclemos non ? reprit l&apos;homme, affichant un air soupçonneux.<br/> - Nous la célébrons par nos actions, plus tard, nous boirons et chanterons. Ecclemosien, je vous prie de vous écarter et ne plus vous mettre en travers d&apos;un député de l&apos;Ecclemos en mission, à moins que derrière vos beaux discours, vous n&apos;agissiez en réalité pour des intérêts tout autres que ceux de l&apos;Ecclemos. La terreur se lut instantanément sur le visage de l&apos;homme.<br/> - Non, non, Ecclémosien député. Je vous en prie, passez donc, bien sûr. Vive l&apos;Ecclemos ! Allez les gars, reprit-il en direction de ses comparses, c&apos;est l&apos;heure de notre rendez-vous avec monsieur Yattafa, pour l&apos;Ecclemos, ponctua-t-il plus fort. Mashata, ses hommes et Hautbrave purent enfin repartir et entrer dans le hangar qui leur tendait les bras à quelques mètres de là. Dedans, Hautbrave aperçut le Bougainville, prêt à décoller, avec deux autres hommes qui attendaient en bas de la passerelle. <br/> 
        - Enlevez-lui les menottes. Etranger, gagnez votre vaisseau, partez, et ne revenez pas. Si, pour une raison ou une autre, vous deviez revenir, vous trouveriez cette fois et pour de bon la mort. Tenez. L&apos;homme tendit un rouleau scellé.<br/> - Si sur votre route vous tombez sur un garde zélé, donnez-lui ce rouleau. Qu&apos;on ne vous revoit plus. Cette dernière phrase avait été prononcée sur le ton du “au revoir”. Hautbrave se massa les poignets et gagna l&apos;intérieur du Bougainville qu&apos;il inspecta superficiellement pour constater que tout était plus ou moins à sa place. Il s&apos;assit dans le fauteuil de pilotage, fit décoller le vaisseau, rejoignit l&apos;espace et poursuivit sa route sans un regard en arrière.</div>)
}