---
apiVersion: v1
kind: Secret
metadata:
  name: bougainville-secret
  namespace: bougainville
type: Opaque
data:
  psql_user: cG9zdGdyZXM=
  psql_password: cG9zdGdyZXM=
  webdav_user: Ym91Z2FpbnZpbGxl
  webdav_pass: TW91c3F1ZVRhaXJlczM=
  admin_email: ZWQucGFpbGxhcmRAZ21haWwuY29t
  secret_key: RDBIK04xU0pSY2FBS01QM2VvcXhBSVJ0TERPVEZPWjV2b3ZDNzd1S25zNEl1VkJCYXV6TUFJcDBML1NBcWs1Wg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bougainville-configmap
  namespace: bougainville
data:
  psql_dbname: bougainville
  psql_host: bougainville-postgres-service
  psql_port: '5432'
  backend_url: '162.19.66.30'
  backend_port: '5000'
  webdav_url: '162.19.66.30'
