apiVersion: apps/v1
kind: Deployment
metadata:
  name: boug-server-deploy
  labels:
    app: boug-server
  namespace: bougainville
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boug-server
  template:
    metadata:
      labels:
        app: boug-server
    spec:
      containers:
      - name: boug-server
        image: 162.19.66.30:7000/boug_server:v0.0.30
        ports:
        - containerPort: 4001
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: bougainville-secret
                key: psql_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bougainville-secret
                key: psql_password
          - name: WEBDAV_USER
            valueFrom:
              secretKeyRef:
                name: bougainville-secret
                key: webdav_user
          - name: WEBDAV_PASS
            valueFrom:
              secretKeyRef:
                name: bougainville-secret
                key: webdav_pass
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: bougainville-configmap
                key: psql_dbname
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: bougainville-configmap
                key: psql_host
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: bougainville-configmap
                key: psql_port
          - name: WEBDAV_URL
            valueFrom:
              configMapKeyRef:
                name: bougainville-configmap
                key: webdav_url
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: bougainville-secret
                key: admin_email
          - name: REACT_APP_SECRET_KEY
              valueFrom:
              secretKeyRef:
                name: bougainville-secret
                key: secret_key

  
