apiVersion: v1
kind: Service
metadata:
  name: bougainville-server-service
  labels:
    app: bougainville-server-service
  namespace: bougainville
spec:
  type: LoadBalancer
  selector:
    app: boug-server
  ports:
    - name: http-back
      port: 5000
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: bougainville-client-service
  labels:
    app: bougainville-client-service
  namespace: bougainville
spec:
  type: LoadBalancer
  selector:
      app: boug-client
  ports:
    - name: http-client
      port: 3000
      targetPort: 3000
--- 
apiVersion: v1
kind: Service
metadata:
  name: bougainville-postgres-service
  labels:
    app: bougainville-postgres-service
  namespace: bougainville
spec:
  selector:
    app: boug-psql
  ports:
    - port: 5432
      targetPort: 5432
